# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
          "android.injected.signing.store.file" => "/Users/fujikinaga/key.jks",
          "android.injected.signing.store.password" => "fujikinaga",
          "android.injected.signing.key.alias" => "key",
          "android.injected.signing.key.password" => "fujikinaga",
        }
    )
    firebase_app_distribution(
              app: "1:1090258945629:android:53990f2a1332638c626fb4",
              groups: "me",
              apk_path: "../build/app/outputs/apk/release/app-release.apk",
              firebase_cli_path: "/usr/local/bin/firebase"
            )
    slack(message: 'Successfully beta Android workflow',
          slack_url: "https://hooks.slack.com/services/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")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
          "android.injected.signing.store.file" => "/Users/fujikinaga/key.jks",
          "android.injected.signing.store.password" => "fujikinaga",
          "android.injected.signing.key.alias" => "key",
          "android.injected.signing.key.password" => "fujikinaga",
        }
    )
    upload_to_play_store(
      track: 'beta',
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
    slack(message: 'Successfully distributed a new beta Android build',
          slack_url: "https://hooks.slack.com/services/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")
  end
end
