# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
              app:"1:1090258945629:android:53990f2a1332638c626fb4",
              groups:"me",
              firebase_cli_path:"/usr/local/bin/firebase"
            )
    slack(message: 'Successfully beta Android workflow',
          slack_url: "https://hooks.slack.com/services/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")
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
    slack(message: 'Successfully distributed a new beta Android build',
          slack_url: "https://hooks.slack.com/services/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")
  end
end
