name: flutter_build_and_deploy_and_test_android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channcel: 'beta'

      - name: Create key.properties
        run: |
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' > android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=key' >> android/key.properties
          echo 'storeFile=key.jks' >> android/key.properties
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk
      - name: Archive apk
        uses: actions/upload-artifact@v1
        with:
          name: app.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install Firebase
        run: yarn install
      - name: Upload APK
        run: yarn run firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk --app "${{ secrets.FIREBASE_ANDROID_APP_ID }}" --groups GROUP --token "${{ secrets.FIREBASE_DEV_TOKEN }}"

  firebase:
    name: Run Test on Firebase Test Lab
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download APK
        uses: actions/download-artifact@v1
        with:
          name: app.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          export_default_credentials: true
      - run: gcloud info

      - name: Run Test on Firebase Test Lab
        run: gcloud firebase test android run --type robo --app build/app/outputs/apk/release/app-release.apk --device model=Pixel2,version=28,locale=ja,orientation=portrait